### ISSUE TITLE
Segmentation fault [memory leak]

### ISSUE THREAD

**Issue by penuel-leo** [onotelli/justniffer#2]
Just run the following this statement：
justniffer -l %source.ip , %dest.ip , %connection.time(0) , %request.timestamp , %response.time(0) , %response.size , %request.method , %request.protocol , %request.header.host(HOST_NOT_FOUND) , %request.url , %request.header.referer(REFERER_NOT_FOUND) , %request.header.user-agent(USER_AGENT_NOT_FOUND) , %response.code , %response.header.value(Location)%newline -i eth0 -p tcp port 80 -e ./append.sh

The memory will always rise, until the occupation of all the memory, the process then down, error is as follows:
Segmentation fault

**Comment by penuel-leo** [comment]
solution:https://github.com/penuel-leo/justniffer

**Comment by wuyouzi** [comment]
@penuel-leo  It works well. Thanks! Good job!

**Comment by onotelli** [comment]
you can control memory usage with the --max-tcp-streams option. 
I
